test: false # if true, only generate 5 concatinated entries
# output dir
output_dir: /data/compaction_integrity/default_ds


dataset: wildchat # details of loading is predefined in loader.py
ds_name: wildchat_cat_100k

# the number of 100k-length conversation in the final dataset
num_convo: 100

stitching_method: topic_cohesive
embedding_cache:
  path: /data/compaction_integrity/topic_cohesive_embedding_cache

# concat: true for short multi-turn ds
concat: true
target_size: 100k # target size of the concatenated dataset
